var PLAYER_AVAILABLE_ITEMS;

var BATTLE_ITEMS_MAPS = {
    "Type Boost Damage": [["Black Belt","hold-item/black-belt"],["Black Glasses","hold-item/black-glasses"],["Charcoal","hold-item/charcoal"],["Dragon Fang","hold-item/dragon-fang"],["Hard Stone","hold-item/hard-stone"],["Never-Melt Ice","hold-item/never-melt-ice"],["Magnet","hold-item/magnet"],["Metal Coat","hold-item/metal-coat"],["Miracle Seed","hold-item/miracle-seed"],["Mystic Water","hold-item/mystic-water"],["Poison Barb","hold-item/poison-barb"],["Sharp Beak","hold-item/sharp-beak"],["Silk Scarf","hold-item/silk-scarf"],["Spell Tag","hold-item/spell-tag"],["Silver Powder","hold-item/silver-powder"],["Soft Sand","hold-item/soft-sand"],["Twisted Spoon","hold-item/twisted-spoon"]],
    "Held Item": [["Razor Claw","evo-item/razor-claw"],["Razor Fang","evo-item/razor-fang"],["Absorb Bulb","hold-item/absorb-bulb"],["Adamant Orb","hold-item/adamant-orb"],["Adrenaline Orb","hold-item/adrenaline-orb"],["Air Balloon","hold-item/air-balloon"],["Assault Vest","hold-item/assault-vest"],["Big Root","hold-item/big-root"],["Binding Band","hold-item/binding-band"],["Black Sludge","hold-item/black-sludge"],["Blue Orb","hold-item/blue-orb"],["Blunder Policy","hold-item/blunder-policy"],["Bright Powder","hold-item/bright-powder"],["Cell Battery","hold-item/cell-battery"],["Choice Band","hold-item/choice-band"],["Choice Scarf","hold-item/choice-scarf"],["Choice Specs","hold-item/choice-specs"],["Destiny Knot","hold-item/destiny-knot"],["Eject Button","hold-item/eject-button"],["Eject Pack","hold-item/eject-pack"],["Eviolite","hold-item/eviolite"],["Expert Belt","hold-item/expert-belt"],["Flame Orb","hold-item/flame-orb"],["Float Stone","hold-item/float-stone"],["Focus Band","hold-item/focus-band"],["Focus Sash","hold-item/focus-sash"],["Grip Claw","hold-item/grip-claw"],["Griseous Orb","hold-item/griseous-orb"],["Iron Ball","hold-item/iron-ball"],["Lagging Tail","hold-item/lagging-tail"],["Leftovers","hold-item/leftovers"],["Life Orb","hold-item/life-orb"],["Light Clay","hold-item/light-clay"],["Luminous Moss","hold-item/luminous-moss"],["Lustrous Orb","hold-item/lustrous-orb"],["Metronome","hold-item/metronome"],["Muscle Band","hold-item/muscle-band"],["Power Herb","hold-item/power-herb"],["Mental Herb","hold-item/mental-herb"],["Protective Pads","hold-item/protective-pads"],["Quick Claw","hold-item/quick-claw"],["Red Card","hold-item/red-card"],["Red Orb","hold-item/red-orb"],["Ring Target","hold-item/ring-target"],["Rocky Helmet","hold-item/rocky-helmet"],["Room Service","hold-item/room-service"],["Safety Goggles","hold-item/safety-goggles"],["Scope Lens","hold-item/scope-lens"],["Shed Shell","hold-item/shed-shell"],["Shell Bell","hold-item/shell-bell"],["Snowball","hold-item/snowball"],["Sticky Barb","hold-item/sticky-barb"],["Throat Spray","hold-item/throat-spray"],["Toxic Orb","hold-item/toxic-orb"],["Utility Umbrella","hold-item/utility-umbrella"],["Weakness Policy","hold-item/weakness-policy"],["White Herb","hold-item/white-herb"],["Wide Lens","hold-item/wide-lens"],["Wise Glasses","hold-item/wise-glasses"],["Zoom Lens","hold-item/zoom-lens"],["Full Incense","incense/full"],["Lax Incense","incense/lax"],["Odd Incense","incense/odd"],["Rock Incense","incense/rock"],["Rose Incense","incense/rose"],["Sea Incense","incense/sea"],["Wave Incense","incense/wave"],["Electric Seed","hold-item/electric-seed"],["Grassy Seed","hold-item/grassy-seed"],["Misty Seed","hold-item/misty-seed"],["Psychic Seed","hold-item/psychic-seed"]],
    "Berries": [["Cheri Berry","berry/cheri"],["Chesto Berry","berry/chesto"],["Pecha Berry","berry/pecha"],["Rawst Berry","berry/rawst"],["Aspear Berry","berry/aspear"],["Persim Berry","berry/persim"],["Lum Berry","berry/lum"],["Leppa Berry","berry/leppa"],["Oran Berry","berry/oran"],["Sitrus Berry","berry/sitrus"],["Figy Berry","berry/figy"],["Wiki Berry","berry/wiki"],["Mago Berry","berry/mago"],["Aguav Berry","berry/aguav"],["Iapapa Berry","berry/iapapa"],["Liechi Berry","berry/liechi"],["Ganlon Berry","berry/ganlon"],["Petaya Berry","berry/petaya"],["Apicot Berry","berry/apicot"],["Salac Berry","berry/salac"],["Lansat Berry","berry/lansat"],["Starf Berry","berry/starf"],["Custap Berry","berry/custap"],["Enigma Berry","berry/enigma"],["Jaboca Berry","berry/jaboca"],["Kee Berry","berry/kee"],["Maranga Berry","berry/maranga"],["Micle Berry","berry/micle"],["Razz Berry","berry/razz"],["Rowap Berry","berry/rowap"]],
    "Plates": [["Draco Plate","plate/draco"],["Dread Plate","plate/dread"],["Earth Plate","plate/earth"],["Fist Plate","plate/fist"],["Flame Plate","plate/flame"],["Icicle Plate","plate/icicle"],["Insect Plate","plate/insect"],["Iron Plate","plate/iron"],["Meadow Plate","plate/meadow"],["Mind Plate","plate/mind"],["Pixie Plate","plate/pixie"],["Sky Plate","plate/sky"],["Splash Plate","plate/splash"],["Spooky Plate","plate/spooky"],["Stone Plate","plate/stone"],["Toxic Plate","plate/toxic"],["Zap Plate","plate/zap"]],
    "Damage Reducing Berries": [["Babiri Berry","berry/babiri"],["Charti Berry","berry/charti"],["Chilan Berry","berry/chilan"],["Chople Berry","berry/chople"],["Coba Berry","berry/coba"],["Colbur Berry","berry/colbur"],["Haban Berry","berry/haban"],["Kasib Berry","berry/kasib"],["Kebia Berry","berry/kebia"],["Occa Berry","berry/occa"],["Passho Berry","berry/passho"],["Payapa Berry","berry/payapa"],["Rindo Berry","berry/rindo"],["Roseli Berry","berry/roseli"],["Shuca Berry","berry/shuca"],["Tanga Berry","berry/tanga"],["Wacan Berry","berry/wacan"],["Yache Berry","berry/yache"]],
    "Gems": [["Bug Gem","gem/bug"],["Dark Gem","gem/dark"],["Dragon Gem","gem/dragon"],["Electric Gem","gem/electric"],["Fairy Gem","gem/fairy"],["Fighting Gem","gem/fighting"],["Fire Gem","gem/fire"],["Flying Gem","gem/flying"],["Ghost Gem","gem/ghost"],["Grass Gem","gem/grass"],["Ground Gem","gem/ground"],["Ice Gem","gem/ice"],["Normal Gem","gem/normal"],["Poison Gem","gem/poison"],["Psychic Gem","gem/psychic"],["Rock Gem","gem/rock"],["Steel Gem","gem/steel"],["Water Gem","gem/water"]],
    "Terrain modificators": [["Smooth Rock","hold-item/smooth-rock"],["Damp Rock","hold-item/damp-rock"],["Heat Rock","hold-item/heat-rock"],["Icy Rock","hold-item/icy-rock"],["Terrain Extender","hold-item/terrain-extender"]],
    "Mega-Stone": [["Abomasite","mega-stone/abomasite"],["Absolite","mega-stone/absolite"],["Aerodactylite","mega-stone/aerodactylite"],["Aggronite","mega-stone/aggronite"],["Alakazite","mega-stone/alakazite"],["Altarianite","mega-stone/altarianite"],["Ampharosite","mega-stone/ampharosite"],["Audinite","mega-stone/audinite"],["Banettite","mega-stone/banettite"],["Beedrillite","mega-stone/beedrillite"],["Blastoisinite","mega-stone/blastoisinite"],["Blazikenite","mega-stone/blazikenite"],["Cameruptite","mega-stone/cameruptite"],["Charizardite X","mega-stone/charizardite-x"],["Charizardite Y","mega-stone/charizardite-y"],["Diancite","mega-stone/diancite"],["Galladite","mega-stone/galladite"],["Garchompite","mega-stone/garchompite"],["Gardevoirite","mega-stone/gardevoirite"],["Gengarite","mega-stone/gengarite"],["Glalitite","mega-stone/glalitite"],["Gyaradosite","mega-stone/gyaradosite"],["Heracronite","mega-stone/heracronite"],["Houndoominite","mega-stone/houndoominite"],["Kangaskhanite","mega-stone/kangaskhanite"],["Latiasite","mega-stone/latiasite"],["Latiosite","mega-stone/latiosite"],["Lopunnite","mega-stone/lopunnite"],["Lucarionite","mega-stone/lucarionite"],["Manectite","mega-stone/manectite"],["Mawilite","mega-stone/mawilite"],["Medichamite","mega-stone/medichamite"],["Metagrossite","mega-stone/metagrossite"],["Mewtwonite X","mega-stone/mewtwonite-x"],["Mewtwonite Y","mega-stone/mewtwonite-y"],["Pidgeotite","mega-stone/pidgeotite"],["Pinsirite","mega-stone/pinsirite"],["Sablenite","mega-stone/sablenite"],["Salamencite","mega-stone/salamencite"],["Sceptilite","mega-stone/sceptilite"],["Scizorite","mega-stone/scizorite"],["Sharpedonite","mega-stone/sharpedonite"],["Slowbronite","mega-stone/slowbronite"],["Steelixite","mega-stone/steelixite"],["Swampertite","mega-stone/swampertite"],["Tyranitarite","mega-stone/tyranitarite"],["Venusaurite","mega-stone/venusaurite"]],
    "Z-item": [["Aloraichium Z","z-crystals/aloraichium-z--held"],["Buginium Z","z-crystals/buginium-z--held"],["Darkinium Z","z-crystals/darkinium-z--held"],["Decidium Z","z-crystals/decidium-z--held"],["Dragonium Z","z-crystals/dragonium-z--held"],["Eevium Z","z-crystals/eevium-z--held"],["Electrium Z","z-crystals/electrium-z--held"],["Fairium Z","z-crystals/fairium-z--held"],["Fightinium Z","z-crystals/fightinium-z--held"],["Firium Z","z-crystals/firium-z--held"],["Flyinium Z","z-crystals/flyinium-z--held"],["Ghostium Z","z-crystals/ghostium-z--held"],["Grassium Z","z-crystals/grassium-z--held"],["Groundium Z","z-crystals/groundium-z--held"],["Icium Z","z-crystals/icium-z--held"],["Incinium Z","z-crystals/incinium-z--held"],["Kommonium Z","z-crystals/kommonium-z--held"],["Lunalium Z","z-crystals/lunalium-z--held"],["Lycanium Z","z-crystals/lycanium-z--held"],["Marshadium Z","z-crystals/marshadium-z--held"],["Mewnium Z","z-crystals/mewnium-z--held"],["Mimikium Z","z-crystals/mimikium-z--held"],["Normalium Z","z-crystals/normalium-z--held"],["Pikanium Z","z-crystals/pikanium-z--held"],["Pikashunium Z","z-crystals/pikashunium-z--held"],["Poisonium Z","z-crystals/poisonium-z--held"],["Primarium Z","z-crystals/primarium-z--held"],["Psychium Z","z-crystals/psychium-z--held"],["Rockium Z","z-crystals/rockium-z--held"],["Snorlium Z","z-crystals/snorlium-z--held"],["Solganium Z","z-crystals/solganium-z--held"],["Steelium Z","z-crystals/steelium-z--held"],["Tapunium Z","z-crystals/tapunium-z--held"],["Ultranecrozium Z","z-crystals/ultranecrozium-z--held"],["Waterium Z","z-crystals/waterium-z--held"]],
    "Memories": [["Bug Memory","memory/bug"],["Dark Memory","memory/dark"],["Dragon Memory","memory/dragon"],["Electric Memory","memory/electric"],["Fairy Memory","memory/fairy"],["Fighting Memory","memory/fighting"],["Fire Memory","memory/fire"],["Flying Memory","memory/flying"],["Ghost Memory","memory/ghost"],["Grass Memory","memory/grass"],["Ground Memory","memory/ground"],["Ice Memory","memory/ice"],["Poison Memory","memory/poison"],["Psychic Memory","memory/psychic"],["Rock Memory","memory/rock"],["Steel Memory","memory/steel"],["Water Memory","memory/water"]],
    "Pokemon Specific": [["Deep Sea Scale","evo-item/deep-sea-scale"],["Deep Sea Tooth","evo-item/deep-sea-tooth"],["Burn Drive","hold-item/burn-drive"],["Chill Drive","hold-item/chill-drive"],["Douse Drive","hold-item/douse-drive"],["Shock Drive","hold-item/shock-drive"],["Light Ball","hold-item/light-ball"],["Lucky Punch","hold-item/lucky-punch"],["Metal Powder","hold-item/metal-powder"],["Quick Powder","hold-item/quick-powder"],["Rusted Shield","hold-item/rusted-shield"],["Rusted Sword","hold-item/rusted-sword"],["Thick Club","hold-item/thick-club"],["Soul Dew","hold-item/soul-dew"],["Stick","hold-item/stick"],],
    "Power Level": [["Macho Brace","ev-item/macho-brace"],["Power Anklet","ev-item/power-anklet"],["Power Band","ev-item/power-band"],["Power Belt","ev-item/power-belt"],["Power Bracer","ev-item/power-bracer"],["Power Lens","ev-item/power-lens"],["Power Weight","ev-item/power-weight"]]
}

function populateItemBox() {
    var itemBox = document.getElementById("item-box-body")
    var strFrag = ""
    for (var entry in BATTLE_ITEMS_MAPS){
        strFrag += '<legend>' + entry + '</legend>'
        strFrag+= '<img class="ic" src="../img/none.png" data-id="">'
        BATTLE_ITEMS_MAPS[entry].forEach(function(value, key){
            if (PLAYER_AVAILABLE_ITEMS.includes(key)){
                strFrag += '<img class="ic" src="https://raw.githubusercontent.com/msikma/pokesprite/master/items/' + value + '.png" loading="lazy" data-id="' + key + '">';
            }
        });
        strFrag += '<hr>'
    };
    itemBox.innerHTML = strFrag;
    $('.ic').click(selectItem);
    $('.ic').click(saveTrigger);
    
}

function deserializeBattleItems() {
    for (var entry in BATTLE_ITEMS_MAPS){
        BATTLE_ITEMS_MAPS[entry] = new Map(BATTLE_ITEMS_MAPS[entry]);
    };
}
$(document).ready(function(){
    PLAYER_AVAILABLE_ITEMS = PLAYER_AVAILABLE_ITEMS || items;
    deserializeBattleItems()
    // load images asynchronously to not hinder the loading speed
    setTimeout(populateItemBox, 0);
});