#!/bin/bash -xe

# Setup

rev=$(git rev-parse --short HEAD | tr -d "\n")

# Build

node build

# Checkout: main -> gh-pages

git checkout gh-pages

# Publish

cp -a dist/* .

git add -A .
git commit -m "Publish: '${rev}'"
git push git@github.com:forwardfeed/redux-elite-calc.git 
# Checkout: gh-pages -> main

git checkout main
